name: 'qhome-base-app'

services:
  qhomeapp-postgres:
    image: postgres:13
    container_name: qhomeapp-postgres
    environment:
      POSTGRES_DB: qhome_base_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0035
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5433:5432"
    volumes:
      - app-pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d qhome_base_db -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  qhomeapp-rabbitmq:
    image: rabbitmq:4.0.4-management
    container_name: qhomeapp-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - app-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 30s
      retries: 10

  qhomeapp-mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: qhomeapp-mailhog
    ports:
      - "1026:1025"
      - "8026:8025"
    networks:
      - app-network

  qhomeapp-keycloak:
    image: quay.io/keycloak/keycloak:26.3.0
    container_name: qhomeapp-keycloak
    command: [ "start-dev", "--import-realm", "--http-port=9192" ]
    hostname: keycloak-app
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin1234
    ports:
      - "9192:9192"
    networks:
      - app-network

  api-gateway-app:
    build:
      context: ../../api-gateway-app
      dockerfile: Dockerfile
    container_name: api-gateway-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "9001:9001"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      qhomeapp-postgres:
        condition: service_healthy

  login-service:
    build:
      context: ../../
      dockerfile: login-service/Dockerfile
    container_name: login-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://qhomeapp-postgres:5432/qhome_base_db?currentSchema=login
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0035
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      qhomeapp-postgres:
        condition: service_healthy

volumes:
  app-pgdata:
  app-rabbitmq-data:

networks:
  app-network: